context: {}

gatewayclasses:
  default:
    enabled: true
    spec:
      controllerName: example.net/gateway-controller

gateways:
  main:
    enabled: true
    metadata:
      namespace: default
    spec:
      gatewayClassName: default
      listeners:
        - name: http
          protocol: HTTP
          port: 80
        - name: https
          protocol: HTTPS
          port: 443
          tls:
            mode: Terminate
            certificateRefs:
              - name: my-cert

httproutes:
  web:
    enabled: true
    spec:
      parentRefs:
        - name: main
      hostnames:
        - "example.com"
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: web-service
              port: 80

settings:
  gateways:
    defaults:
      metadata:
        namespace: default
      spec:
        gatewayClassName: default
        listeners: []
