resources:
  #: v1
  configmaps:
    apiVersion: v1
    kind: ConfigMap
    jsonSchemaRef: metachart.api.io.k8s.api.core.v1.ConfigMap
  services:
    apiVersion: v1
    kind: Service
    jsonSchemaRef: metachart.api.io.k8s.api.core.v1.Service

  #: apps/v1
  deployments:
    apiVersion: apps/v1
    kind: Deployment
    jsonSchemaRef: metachart.api.io.k8s.api.apps.v1.Deployment
