.defaults:
  disallowed: &defaultDisallowed
    - status
    - kind
    - apiVersion
  properties: &defaultProperties
    enabled: metachart.interface.boolean
    metadata: metachart.api.meta.v1.ObjectMeta
  rootKey: &defaultRootKey
    disallowed: *defaultDisallowed
    properties: *defaultProperties

definitions:
  - https://raw.githubusercontent.com/iponweb/schemas/main/json-schemas/external-secrets/v0.6.1-strict/_definitions.json

rules:
  #: Common
  #:
  #: meta.v1.ObjectMeta
  - target: metachart.api.meta.v1.ObjectMeta
    source: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    allowed:
      - annotations
      - labels
      - finalizers
      - namespace
      - name
    properties:
      checksums: metachart.interface.checksums

  #: v1
  - target: metachart.api.io.k8s.api.core.v1.ConfigMap
    source: io.k8s.api.core.v1.ConfigMap
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.core.v1.Service
    source: io.k8s.api.core.v1.Service
    <<: *defaultRootKey
  #: v1 - Pod
  - target: metachart.api.core.v1.Pod
    source: io.k8s.api.core.v1.Pod
    disallowed: *defaultDisallowed
    properties:
      <<: *defaultProperties
      spec: metachart.api.core.v1.PodSpec
  - target: metachart.api.core.v1.PodSpec
    source: io.k8s.api.core.v1.PodSpec
    properties:
      metadata: metachart.api.meta.v1.ObjectMeta

  #: apps/v1
  - target: metachart.api.io.k8s.api.apps.v1.Deployment
    source: io.k8s.api.apps.v1.Deployment
    disallowed: *defaultDisallowed

    #: Use overridden DeploymentSpec definition
    properties:
      <<: *defaultProperties
      spec: metachart.api.io.k8s.api.apps.v1.DeploymentSpec
    #: Defined resources kinds which can be related
    related:
      services: metachart.api.io.k8s.api.core.v1.Service
  - target: metachart.api.io.k8s.api.apps.v1.DeploymentSpec
    source: io.k8s.api.apps.v1.DeploymentSpec
    disallowed:
      #: selector will be set by the Deployment preprocessor
      - selector
    properties:
      template: metachart.api.core.v1.Pod
